https://plantuml.com/ru/sequence-diagram
@startuml

Клиент -> Сервер : Рукопожатие (HTTP Upgrade)
Сервер ->> Клиент : Открывается WebSocket\nсоединение
Клиент --> Сервер : Сообщение
Клиент --> Сервер : Сообщение
Клиент --> Сервер : Сообщение
Сервер --> Клиент : Сообщение
Клиент ->> Сервер : Закрывается WebSocket\nсоединение

@enduml